### ISSUE TITLE
Question on route handlers

### ISSUE THREAD

**Issue by srconklin** [larrymyers/react-mini-router#12]
This is not  an issue but really just a question.  Firstly, I want to say that i love the simplicity behind react-min-router.. it is working very well for me.. 

So, I have render method written like so to include wrap the current wrap into a header /footer:

 render : function () {

        return (
  		 <div className="container">
                   <div className="page-header">
                       <h1>Header</h1>
                       <a href="/">default page</a> | <a href="/section/page1">page 1</a>
                   </div>
                  {this.renderCurrentRoute()}
                  <div className="footerWrapper">
                      <h2>This is a footer</h2>
                  </div>
  		 </div>
  		);
  	}

Now, i want to have a route (login) that should just render itself and nothing else. (The login page should show only login form. i.e. no standard layout.)

Can you tell me how i would best accomplish this?

**Comment by larrymyers** [comment]
The RouterMixin was designed to be used at the top level root component of an app. You can add your auth check in the root component's render method, and do conditional rendering there.

I'd have to think through pre/post callbacks for route handlers to see if it's possible to augment the existing v1.0 API without requiring a major version bump. 

Code example:

```javascript
var MyApp = React.createClass({

    mixins: [RouterMixin],

    render: function() {
        if (mustLogin) {
            return this.renderLogin();
        } else {
            return <div>{this.renderCurrentRoute()}</div>;
        }
    }

});
```

**Comment by srconklin** [comment]
thanks.. i came to the same conclusion after playing around with it for a while.
