### ISSUE TITLE
Reacting to route change

### ISSUE THREAD

**Issue by stlk** [larrymyers/react-mini-router#20]
I have an flux app where I would like to call state altering action when certain route is "requested". Is there a place to do this outside of render method? Something like onNavigate.

Thank you!

**Comment by larrymyers** [comment]
If you have an action that alters the app state I would manually do a call to ReactMiniRouter.navigate after the action completes. That will explicitly change the url in response to a state change, and as a result call setState on the Component the RouterMixin is attached to.

Specifically in the case of the Flux pattern you'll likely want to do this in the action handler, not the Store.

**Comment by stlk** [comment]
Sounds reasonable. Thanks for suggestion!
