### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by kkarimi** [larrymyers/react-mini-router#27]
The mini-router does not seem to support IE8 out of the box. However It looks at least it loads without errors if you catch addEventListeners using [this method](http://stackoverflow.com/questions/9769868/addeventlistener-not-working-in-ie8) but still the links do not redirect, possibly because of hashes in the URL. Has anyone had any success using this with IE8 or any tips? Thanks

**Comment by larrymyers** [comment]
Just to clarify are you seeing js errors, or just functionality not working as expected?

**Comment by larrymyers** [comment]
Resolved with 1.1.4 release. Published to npm and bower.
