### ISSUE TITLE
Get error in IE11

### ISSUE THREAD

**Issue by samsam2310** [larrymyers/react-mini-router#33]
I get and error in ie11.
I found that you use ```new Event()``` which not support in ie in line 315(version 1.1.5).
How can I fix it?

**Comment by larrymyers** [comment]
Verified bug. Will slot in the fix for the 1.1.6 milestone.

**Comment by larrymyers** [comment]
https://msdn.microsoft.com/en-us/library/dn905219(v=vs.85).aspx

**Comment by samsam2310** [comment]
Ok,thanks.

**Comment by larrymyers** [comment]
Fixed by #34

**Comment by timReynolds** [comment]
I could do with this fix being deployed, is there anything stopping 1.1.6 being tagged?

**Comment by larrymyers** [comment]
Done. Change log updated, 1.1.6 available through bower and npm.
