### ISSUE TITLE
Links not working in IE8?

### ISSUE THREAD

**Issue by kkarimi** [larrymyers/react-mini-router#37]
Hi Larry,
Just testing with IE8 and the links are not working for me. The routing in general seems to be fine but when I click a normal link, it just goes to the /url without the hashbang (works fine in Chrome of course). Any ideas why this is happening?

From a quick look getHref function does not seem to return a URL in IE8 but I might be looking at the wrong thing.

Many thanks,

**Comment by larrymyers** [comment]
There are plenty of cases in getHref where it will return undefined instead of the url. This is to prevent the router from intercepting links that point to external resources instead of registered routes.

Can you provide a working example where this fails?

**Comment by kkarimi** [comment]
Yes sure, I think my issue is that all links are considered as external for some reason, maybe I have set it up wrong?
So here is my code:
https://github.com/kkarimi/react-mini-router-IE8-test
and I have put up the build here:
https://kkarimi.github.io/react-mini-router-IE8-test
Visiting the page in real IE8 under virtualbox shows the problem (links don't work).

**Comment by larrymyers** [comment]
Looks like it may be due to RouterMixin.js line 182, with IE 8 not having a target property on Event, but instead srcElement. I should have some time this week to get a fix tested and pushed to npm.

**Comment by kkarimi** [comment]
I believe you are right about the srcElement on IE8, a fix release would be great, many thanks.

**Comment by larrymyers** [comment]
Fixed. 1.1.7 published to npm and bower.

**Comment by kkarimi** [comment]
Thanks Larry, although I did a quick test and it did not seem to work out of the box, I will run it through debugger and get back to you tomorrow.
