### ISSUE TITLE
Conflict with react-bootstrap

### ISSUE THREAD

**Issue by kkarimi** [larrymyers/react-mini-router#42]
It seems that there is a weird conflict between react-mini-router and the popuar react-bootstrap, for the full problem please see [here](https://github.com/react-bootstrap/react-bootstrap/issues/1331).

To replicate the problem you can go to [here](http://test.karimi.info/#!/About) ([source](https://github.com/kkarimi/react-bootstrap-test/blob/master/src/js/components/Header.jsx)). Pressing the dropdown when you are on the about page, the app navigates back to home. 

I have tried to debug the RouterMixin but with little success. Do you have any ideas? Thanks

**Comment by kkarimi** [comment]
So with a quick hack I have modified the handeClick like this and it fixes the problem temporarily.. 
```javascript
handleClick: function(evt) {
    var dropdownevt = (evt.path[0].id === 'acc-dropdown');
        if (url && self.matchRoute(url.pathname) && !dropdownevt) {    ...
```

**Comment by molson504x** [comment]
@kkarimi Have you tried creating the dropdown button without using an anchor tag?  Or without putting the href attribute in your anchor tag?
