### ISSUE TITLE
use high-order-component instead of mixin

### ISSUE THREAD

**Issue by jzlxiaohei** [larrymyers/react-mini-router#43]
any plans?

**Comment by larrymyers** [comment]
It's something that I'd certainly like to tackle in the future with the use of Mixins going away when ES6 classes are used for components, but it's not something that I have planned anytime soon, especially while the React API is still changing in this pre-1.0 release phase.

I'd happily accept any pull requests that gets this work started.

**Comment by larrymyers** [comment]
No response from @jzlxiaohei . Closing.
