### ISSUE TITLE
Pre route hook

### ISSUE THREAD

**Issue by killfish** [larrymyers/react-mini-router#45]
Is there a pre route method to hook into? I would like to check if some form content on a page "is dirty/not saved" and alert the user if they click the browser back/forward button.

**Comment by larrymyers** [comment]
There currently aren't any pre/post hooks provided. You can certainly store user input in localStorage (or some other form of local browser storage), and use it as a cache, that way your application can restore the form input on back button, forward button, page reload, etc.
