### ISSUE TITLE
Support React 0.14

### ISSUE THREAD

**Issue by jakoblind** [larrymyers/react-mini-router#46]
Hi,

After upgrading to React 0.14 I get the following error message:

  ERROR in ./~/react-mini-router/lib/RouterMixin.js
    Module not found: Error: Cannot resolve module 'react/lib/EventListener' in /path/to/project/node_modules/react-mini-router/lib
     @ ./~/react-mini-router/lib/RouterMixin.js 2:20-54

**Comment by larrymyers** [comment]
I'm guessing this has to do with the separation of react and react-dom for 0.14.

I don't have a ton of time to devote to this issue immediately, so a pull request to get this library supported with 0.14 would be welcome.

**Comment by molson504x** [comment]
All you should have to do is require('react-dom')?  Or am I mistaking something.....

**Comment by larrymyers** [comment]
I've tracked down where the functions from React that RouterMixin have moved to, though I'm still in the process of cleaning up all the tests and the example app.  It's not a straight forward process since the team at Facebook have broken a few things from a compatibility standpoint.

**Comment by ykka** [comment]
Yep, @larrymyers any estimation when you might finish making it compatible? Thanks!

**Comment by larrymyers** [comment]
No estimate right now. There are still errors in the exam

**Comment by ykka** [comment]
I might do actually, I've just ditched the `react-router`... `mini-router` gives me much more flexibility I think.

I might look into it over the weekend if I find time.

**Comment by bragin** [comment]
react-mini-router is just great compared to the monstrous react-router.

A very simple fix is to introduce a dependency to fbjs package, where they moved the EventListener.js module to, and fix corresponding require in the RouterMixin.js like this:
EventListener = require('fbjs/lib/EventListener'),

I am just testing the result, but it seems to work as expected. Please share your thoughts, maybe it's just pure magic.

**Comment by ykka** [comment]
Hey, so @bragin (@larrymyers) to me it seems to work, any chances of merging it to `master` soon?

**Comment by ykka** [comment]
Actually, I was wrong, it does seem to fail in my project. So I am not sure if it works or not.. I don't have enough time to look into it atm, sorry!

**Comment by larrymyers** [comment]
Todo for 0.14 Support:

- [] Fix bugs in example app.
- [] Run tests across Chrome, Safari, Firefox, IE 11, and IE 9
- [] Verify compatibility with 0.12 and 0.13, or determine if this release will be 2.0.0
- [] Update changelog and readme

**Comment by jakoblind** [comment]
Any progress on this?

**Comment by larrymyers** [comment]
The day job has me almost completely occupied right now. I'd welcome any help by having pull requests target the react-0.14-upgrade branch.

**Comment by jakoblind** [comment]
I have fixed the bugs in example app and made a pull request #49 . I have tested in Safari, Firefox and Chrome and it works fine!

react-mini-router is not compatible to react 0.12 or 0.13 because it has a dependency to react-dom. So I guess this would be a 2.0.0 release?

The update needed in the Readme would only be the requirement to React 0.14.

**Comment by larrymyers** [comment]
@jakoblind  I agree, a major version bump to 2.0.0 seems like the right decision due to the new dependency on react-dom. Your pull request is merged, so I'll get things ready for release on master and get 2.0.0 pushed out to npm.

**Comment by larrymyers** [comment]
react-mini-router 2.0.0 is live on npm with support for React 0.14. Thanks to @jakoblind for doing all the heavy lifting.
