### ISSUE TITLE
Prototype a RouterComponent to wrap Component

### ISSUE THREAD

**Issue by larrymyers** [larrymyers/react-mini-router#48]
A RouterComponent can be created that wraps the provided Component. The provided routes can be wired to to the Component by doing a setState({ path: path }) on successful routing changes.

http://facebook.github.io/react/docs/reusable-components.html#es6-classes

Example:

https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by peh** [comment]
hey larry,
does the closing mean that this is implemented and can be tested somewhere (i can find no reference in the commit history)

**Comment by larrymyers** [comment]
@peh I closed this because it ended up being work I was never going to get to, nor was a feature request from users of the library.
