### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by adcoolguy** [larrymyers/react-mini-router#54]
A link in the component is ok, but when we hit a back button, the link does not work anymore. Is this a known issue?

**Comment by larrymyers** [comment]
Can you provide more details so I can diagnose?

- What are you using for history support? Hash or pushState?
- Is the link intended to navigate to a registered route?
- Is this across all browsers, or just certain ones?

**Comment by larrymyers** [comment]
No response from @adcoolguy, closing.
