### ISSUE TITLE
Looking for Project Maintainers

### ISSUE THREAD

**Issue by larrymyers** [larrymyers/react-mini-router#68]
react-mini-router is still used enough that it needs more attention than I can give it on a regular basis. If anybody would be interested in doing issue triage, reviewing pull requests, and fixing bugs I will add them as a maintainer for the project.

**Comment by cedmax** [comment]
what kind of help would you need? I wouldn't mind helping out :)

**Comment by larrymyers** [comment]
@cedmax The big needs are reviewing pull requests, triaging issues, and publishing new versions to npm.  It's probably 10-20 hours / month worth of work.  If you're interested I can add you as a maintainer.

**Comment by cedmax** [comment]
I can surely triage the issues and make sure the pull requests make sense. 
One thing I would just suggest, would be to add a eslint configuration, to make sure I comply to the code styles: I'm not familiar with the codebase and I don't really want my opinionated style to creep in (or I can provide a blend one and we could make it stricter as and when).

Anyway, I'd be super happy to help: I think that it's fairly important to keep simpler alternatives to React router, even more after they released v4

**Comment by larrymyers** [comment]
Sounds like a good place to start. I've send you a collaborator invite.

**Comment by cedmax** [comment]
Thanks for the invite: I will spend some time this week sorting the linting out and trying to triage the open issues/PRs, I will be off without connection the first two weeks of April though.
