### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by filippoitaliano** [larrymyers/react-mini-router#76]
Will this module be compatible with React 16?

**Comment by larrymyers** [comment]
@filippoitaliano If you can do the upgrade and provide a pull request that passes the test suite I'll happily accept it.

**Comment by filippoitaliano** [comment]
Probably I'll try soon!

**Comment by Raptortilla** [comment]
I'm using it with React 16 and besides some little modifications of sintax it works like a charm!

**Comment by filippoitaliano** [comment]
Closing for resolution (?) or inactivity.
